---
title: "Utilisation du dépôt `Git`"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">**Objectif et contenu**</h4>
  <p>Présentation rapide des dépôts `Git` pour le développement et la maintenance du SI.</p>
</div>

<div class="alert alert-info" role="alert">
  <h4 class="alert-heading">**Public visé et pré-requis**</h4>
  <p>Développeurs et administrateur du SI SNO-Tourbières.</p>
</div>

# Le dépôt de fichiers `Git` du SI SNO-Tourbières

Les applications et la documentation du projet sont stockées et versionnées dans des dépôts de fichier `Git`. De nombreuses documentations existent pour faciliter l'utilisation de `Git`. Parmi celles-ci, ce [tutoriel](https://openclassrooms.com/courses/gerez-vos-codes-source-avec-git) présente bien les concepts associés à `Git` et guide l'utilisateur pour son utilisation sur windows et linux. Pour une vision complète, consultez la [documentation officielle](https://git-scm.com/book/fr/v2).

## Caractéristiques

Les dépôts `Git` du projet sont hébergés sur [github](https://github.com/rosalien/) : 

- [Documentation du projet](https://github.com/Rosalien/doc_snot)
- [Génération des métadonnées](https://github.com/Rosalien/PivotMetadata_snot)
- [Application data-snot.cnrs.fr](https://github.com/Rosalien/Data_snot)
- [Application data-snot.cnrs.fr/data-access/](https://github.com/Rosalien/dataAccessApp)
- [Application data-snot.cnrs.fr/dataset-archive/](https://github.com/Rosalien/datasetArchiveApp)

# Règle d'organisation du dépôt

Les dépôts sont organisés selon une arborescence qui respecte les règles suivantes :

- le nom des répertoires est le plus explicite possible et ne contient pas d'accents et d'espaces (remplacer par un souligné),
- l'encodage des fichiers textes et des tables (type .csv) est en **UTF-8**,
- *dans la mesure du possible*, chaque nœud de l'arborescence contient un fichier Readme.md (en [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)) qui présente brièvement les répertoires,